plugin:
    name: 'Private Plugins'
    description: 'Download and Install oc-plugins from a remote Repository Git. - Beta'
    author: LucasZdv
    icon: oc-icon-puzzle-piece
    homepage: 'https://awebsome.me'
permissions:
    awebsome.privateplugins.manage_plugins:
        tab: 'awebsome.privateplugins::lang.plugin.name'
        label: 'Can manage private plugins'
